### ISSUE TITLE
引用了不存在的模块

### ISSUE THREAD

**Issue by gitsheny** [Zagrios/regedit-rs#1]
我在跨平台的项目中引入了regedit-rs，在mac系统中打包会报错。js-binding.js中会引用regedit-rs-darwin-arm64，但是这个库不存在。
可以在win32以外的系统中引用regedit-rs时，返回一个空值吗？

**Comment by Zagrios** [comment]
Hi, yeah I can do that but I think its maybe more an issue with NAPI-RS 🤔 

In fact I've already faced this issue in one of my own project, and to handle the error I had to import the pakcage like this (if it can help you for now) :
```ts
const { list } = (execOnOs({ win32: () => require("regedit-rs") }, true) ?? {}) as typeof import("regedit-rs");
```
And the `execOnOs` is a simple fonction :
```ts
export function execOnOs<T>(executions: { [key in ProviderPlatform]?: () => T }, noError = false): T {
    if(executions[process.platform as ProviderPlatform]) {
        return executions[process.platform as ProviderPlatform]();
    }

    if(!noError) {
        throw new Error(`No execution found for platform ${process.platform}`);
    }
}
```

**Comment by gitsheny** [comment]
感谢你的回复。我项目中的某个插件导致我无法直接动态导入模块。于是我把regedit-rs的代码拷贝到了项目中并在内部做了判断，算是解决问题了。
